import Header from '@/components/Header';
import Head from 'next/head';
import Image from 'next/image';

export default function Homepage() {
  return (
    <>
      <Header />
      <Head>
        <title>ApikGems</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div>
          <h6>#1 Trending</h6>
          <h3>Respawn</h3>
          <h1>Apex Legends</h1>
          <p>
            Apex Legends is a free-to-play, hero shooter with an ever expanding
            suite of finely-tuned legendary characters and powerful abilities
            filled with hundreds of cosmetic unlocks to hunt down.
          </p>
          <a>Play Now</a>
          <a>Watch Gameplay</a>
        </div>

        <div>
          {/* <Image
            src="/apex3.png"
            alt="apex3orang"
            height={1444}
            width={1444}
          ></Image> */}
          <img src="/apex3.png"></img>
        </div>
      </div>
    </>
  );
}
