import Header from '@/components/Header';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';

export default function Homepage() {
  return (
    <>
      <Head>
        <title>ApikGems</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <section className="hero">
        <div className="content">
          <div className="main-text">
            <h6>#1 Trending</h6>
            <h3>Epic Games</h3>
            <h1>Fornite</h1>
            <p>
              Fortnite is a world of many experiences. Drop onto the Island and
              compete to be the last player — or team — standing. Create an
              Island of your own with your own rules. Hang out with friends on
              an Island that someone else created. Or save the world by taking
              down hordes of monsters with others.
            </p>

            <Link href="/games">Store</Link>
            <a
              href="https://www.youtube.com/watch?v=P2JnTforl_4&ab_channel=Fortnite"
              className="yutub"
            >
              Watch Trailer
            </a>
          </div>

          <div className="fortnitewrap">
            <Image
              className="fortniteimg"
              src="/fornite.png"
              alt="fortnite img"
              height={1432}
              width={1080}
            ></Image>
          </div>
        </div>
      </section>
    </>
  );
}
